import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(__dirname, "../.env") });

import { prisma } from "../src/db";
import { UserRole, TicketStatus, TicketClassification } from "core/enums";
import { createUser } from "../src/lib/users";

const required = (name: string): string => {
  const value = process.env[name];
  if (!value) throw new Error(`Missing required env var: ${name}`);
  return value;
};

const adminEmail = required("SEED_ADMIN_EMAIL");
const adminPassword = required("SEED_ADMIN_PASSWORD");
const agentEmail = required("SEED_AGENT_EMAIL");
const agentPassword = required("SEED_AGENT_PASSWORD");

async function upsertUser(
  name: string,
  email: string,
  password: string,
  role: UserRole
) {
  const existing = await prisma.user.findUnique({ where: { email } });
  if (existing) {
    console.log(`${role} ${email} already exists — skipping`);
    return;
  }

  await createUser(name, email, password, role);
  console.log(`Created ${role}: ${email}`);
}

const TICKETS: Array<{
  subject: string;
  body: string;
  fromName: string;
  fromEmail: string;
  status: TicketStatus;
  classification: TicketClassification | null;
  createdAt: Date;
}> = [
  // --- Open / TechnicalQuestion ---
  {
    subject: "Cannot log in to my account",
    body: "I've been trying to log in for the past hour but keep getting 'Invalid credentials'. I'm sure my password is correct. Please help.",
    fromName: "Emma Thompson",
    fromEmail: "emma.thompson@gmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2026-01-03T09:12:00Z"),
  },
  {
    subject: "Video player not loading on mobile",
    body: "The course videos don't play on my iPhone 15. I get a spinning loader that never stops. Works fine on my laptop.",
    fromName: "Carlos Mendez",
    fromEmail: "c.mendez@outlook.com",
    status: TicketStatus.Open,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2026-01-05T14:30:00Z"),
  },
  {
    subject: "Quiz results not saving",
    body: "Every time I complete a quiz and click Submit, the page reloads and my answers are gone. My progress is stuck at 0%.",
    fromName: "Priya Sharma",
    fromEmail: "priya.sharma@yahoo.com",
    status: TicketStatus.Open,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2026-01-07T11:45:00Z"),
  },
  {
    subject: "Certificate download gives 404 error",
    body: "I finished the Python Fundamentals course but when I click 'Download Certificate' I get a 404 page.",
    fromName: "David Kim",
    fromEmail: "davidkim@protonmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2026-01-10T08:20:00Z"),
  },
  {
    subject: "Two-factor authentication code not arriving",
    body: "I enabled 2FA last week and now I can't get in. The SMS code never arrives. I've checked my phone number and it's correct.",
    fromName: "Sarah O'Brien",
    fromEmail: "sarah.obrien@icloud.com",
    status: TicketStatus.Open,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2026-01-12T16:05:00Z"),
  },
  {
    subject: "Course progress reset to zero",
    body: "I was 70% through the Advanced JavaScript course and today it shows 0%. I did not unenroll or change anything.",
    fromName: "Liam Walker",
    fromEmail: "liam.walker@gmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2026-01-15T10:00:00Z"),
  },
  {
    subject: "Subtitles not syncing with video",
    body: "The English subtitles in the 'Data Structures' course are about 5 seconds behind the audio. Makes it very hard to follow.",
    fromName: "Aiko Tanaka",
    fromEmail: "aiko.tanaka@gmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2026-01-18T13:22:00Z"),
  },
  {
    subject: "Cannot download course materials as PDF",
    body: "The download button for lesson PDFs does nothing when I click it. I've tried Chrome, Firefox, and Edge.",
    fromName: "Marcus Johnson",
    fromEmail: "marcusj@hotmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2026-01-22T09:50:00Z"),
  },
  {
    subject: "Error when submitting final project",
    body: "Uploading my capstone project ZIP file always fails at 95% with 'Server error'. The file is 48 MB.",
    fromName: "Fatima Al-Hassan",
    fromEmail: "fatima.alhassan@outlook.com",
    status: TicketStatus.Open,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2026-01-25T15:40:00Z"),
  },
  {
    subject: "Playback speed control missing",
    body: "I can no longer change video speed. The option used to be in the player settings but it has disappeared.",
    fromName: "Noah Bennett",
    fromEmail: "noah.bennett@gmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2026-01-28T11:15:00Z"),
  },
  // --- Open / GeneralQuestion ---
  {
    subject: "How long do I have access after purchase?",
    body: "I bought the Web Development Bootcamp. Does my access expire or is it lifetime?",
    fromName: "Olivia Chen",
    fromEmail: "olivia.chen@gmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.GeneralQuestion,
    createdAt: new Date("2026-01-04T10:30:00Z"),
  },
  {
    subject: "Can I take courses offline?",
    body: "I travel frequently and would like to download lessons to watch without internet. Is this possible?",
    fromName: "James Patel",
    fromEmail: "james.patel@yahoo.com",
    status: TicketStatus.Open,
    classification: TicketClassification.GeneralQuestion,
    createdAt: new Date("2026-01-08T14:00:00Z"),
  },
  {
    subject: "Is there a student discount available?",
    body: "I'm a university student on a tight budget. Do you offer any educational discounts?",
    fromName: "Mia Roberts",
    fromEmail: "mia.roberts@student.edu",
    status: TicketStatus.Open,
    classification: TicketClassification.GeneralQuestion,
    createdAt: new Date("2026-01-11T09:45:00Z"),
  },
  {
    subject: "Are courses available in Spanish?",
    body: "My English is basic. Do you have any courses taught in Spanish or with Spanish subtitles?",
    fromName: "Alejandro Ruiz",
    fromEmail: "alex.ruiz@gmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.GeneralQuestion,
    createdAt: new Date("2026-01-14T16:20:00Z"),
  },
  {
    subject: "What is the difference between Basic and Pro plans?",
    body: "I see two subscription tiers but the comparison table is not very clear. Can you explain the key differences?",
    fromName: "Hannah Lee",
    fromEmail: "hannah.lee@outlook.com",
    status: TicketStatus.Open,
    classification: TicketClassification.GeneralQuestion,
    createdAt: new Date("2026-01-19T11:10:00Z"),
  },
  // --- Open / Request ---
  {
    subject: "Request: Add a dark mode to the platform",
    body: "I study late at night and a dark mode would really help reduce eye strain. Please consider adding this feature.",
    fromName: "Ethan Morris",
    fromEmail: "ethan.morris@gmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.Request,
    createdAt: new Date("2026-01-06T08:00:00Z"),
  },
  {
    subject: "Request: Provide course completion certificates",
    body: "I would love a verifiable certificate I can add to my LinkedIn profile when I complete a course.",
    fromName: "Zoe Williams",
    fromEmail: "zoe.w@icloud.com",
    status: TicketStatus.Open,
    classification: TicketClassification.Request,
    createdAt: new Date("2026-01-09T13:30:00Z"),
  },
  {
    subject: "Request: Add a course on machine learning",
    body: "I've completed all your Python courses. A machine learning curriculum would be a natural next step.",
    fromName: "Arjun Singh",
    fromEmail: "arjun.singh@protonmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.Request,
    createdAt: new Date("2026-01-13T10:55:00Z"),
  },
  {
    subject: "Request: Allow pausing and resuming downloads",
    body: "When my internet drops during a lesson download, I have to restart it from scratch. A resume feature would help.",
    fromName: "Isabella Foster",
    fromEmail: "isabella.foster@gmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.Request,
    createdAt: new Date("2026-01-16T15:00:00Z"),
  },
  // --- Open / Refund ---
  {
    subject: "Refund request — accidentally purchased wrong course",
    body: "I meant to buy 'React for Beginners' but ended up purchasing 'React Native'. I haven't started it. Please refund.",
    fromName: "Tom Clarke",
    fromEmail: "tom.clarke@gmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.Refund,
    createdAt: new Date("2026-01-17T09:00:00Z"),
  },
  {
    subject: "Refund — duplicate charge on my card",
    body: "My bank statement shows two charges of $49.99 on January 20th. I only intended to buy one subscription.",
    fromName: "Laura Mitchell",
    fromEmail: "laura.m@outlook.com",
    status: TicketStatus.Open,
    classification: TicketClassification.Refund,
    createdAt: new Date("2026-01-21T12:00:00Z"),
  },
  // --- Open / null classification (unclassified) ---
  {
    subject: "My account was hacked",
    body: "Someone changed my email and password. I can no longer access my account. Please help immediately.",
    fromName: "Daniel Brown",
    fromEmail: "daniel.brown@gmail.com",
    status: TicketStatus.Open,
    classification: null,
    createdAt: new Date("2026-01-23T07:30:00Z"),
  },
  {
    subject: "Billing address update not working",
    body: "Every time I try to save a new billing address in my account settings, I get a 500 error.",
    fromName: "Sophie Turner",
    fromEmail: "sophie.turner@yahoo.com",
    status: TicketStatus.Open,
    classification: null,
    createdAt: new Date("2026-01-26T14:45:00Z"),
  },
  {
    subject: "Profile picture won't upload",
    body: "I've tried JPG and PNG under 1 MB each but the upload just spins and never completes.",
    fromName: "Ryan Cooper",
    fromEmail: "ryan.cooper@hotmail.com",
    status: TicketStatus.Open,
    classification: null,
    createdAt: new Date("2026-01-29T10:20:00Z"),
  },
  // --- Resolved / TechnicalQuestion ---
  {
    subject: "Cannot access purchased course",
    body: "I paid for 'Node.js Masterclass' three days ago but it's not in my library.",
    fromName: "Grace Evans",
    fromEmail: "grace.evans@gmail.com",
    status: TicketStatus.Resolved,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2025-11-02T09:00:00Z"),
  },
  {
    subject: "Payment page crashes on Safari",
    body: "I tried to purchase a course on my MacBook (Safari 17) and the checkout page goes blank after entering card details.",
    fromName: "Henry Adams",
    fromEmail: "henry.adams@icloud.com",
    status: TicketStatus.Resolved,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2025-11-05T11:30:00Z"),
  },
  {
    subject: "Email verification link expired",
    body: "I registered but didn't verify in time. Now the link is expired and there's no option to resend it.",
    fromName: "Chloe Baker",
    fromEmail: "chloe.baker@gmail.com",
    status: TicketStatus.Resolved,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2025-11-08T14:00:00Z"),
  },
  {
    subject: "Audio out of sync in Lesson 7",
    body: "In the 'UX Design Principles' course, lesson 7 has audio that's about 3 seconds ahead of the slides.",
    fromName: "Jack Nelson",
    fromEmail: "jack.nelson@outlook.com",
    status: TicketStatus.Resolved,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2025-11-12T08:45:00Z"),
  },
  {
    subject: "Notifications not working",
    body: "I turned on email notifications for course updates but haven't received any emails in two weeks.",
    fromName: "Ella Carter",
    fromEmail: "ella.carter@yahoo.com",
    status: TicketStatus.Resolved,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2025-11-15T10:20:00Z"),
  },
  {
    subject: "Progress bar stuck at 99%",
    body: "I completed every lesson and quiz but my progress bar won't hit 100%. The certificate button is locked.",
    fromName: "Lucas Green",
    fromEmail: "lucas.green@protonmail.com",
    status: TicketStatus.Resolved,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2025-11-18T13:10:00Z"),
  },
  {
    subject: "Code sandbox not loading in browser",
    body: "The in-browser coding exercises are completely blank for me. I'm using Chrome 120 on Windows 11.",
    fromName: "Nora Phillips",
    fromEmail: "nora.phillips@gmail.com",
    status: TicketStatus.Resolved,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2025-11-21T09:30:00Z"),
  },
  {
    subject: "Wrong video plays in module 4",
    body: "When I click on Lesson 4.3, the video from Lesson 3.1 plays instead.",
    fromName: "Owen Campbell",
    fromEmail: "owen.campbell@hotmail.com",
    status: TicketStatus.Resolved,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2025-11-24T15:55:00Z"),
  },
  {
    subject: "Discount code not applying at checkout",
    body: "I received a promotional code SAVE20 but it says 'Invalid or expired' when I enter it.",
    fromName: "Amelia Scott",
    fromEmail: "amelia.scott@gmail.com",
    status: TicketStatus.Resolved,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2025-11-27T11:00:00Z"),
  },
  {
    subject: "Leaderboard not updating",
    body: "I completed 5 lessons this week but my points on the community leaderboard haven't changed.",
    fromName: "Benjamin Young",
    fromEmail: "ben.young@outlook.com",
    status: TicketStatus.Resolved,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2025-11-30T10:40:00Z"),
  },
  // --- Resolved / GeneralQuestion ---
  {
    subject: "How do I transfer my subscription to a new email?",
    body: "I'm changing jobs and need to move my account to a personal email address.",
    fromName: "Charlotte Hall",
    fromEmail: "charlotte.hall@company.com",
    status: TicketStatus.Resolved,
    classification: TicketClassification.GeneralQuestion,
    createdAt: new Date("2025-11-03T09:15:00Z"),
  },
  {
    subject: "Do you offer team or corporate plans?",
    body: "I manage a dev team of 12. Is there a group licensing option that would work for us?",
    fromName: "William Allen",
    fromEmail: "william.allen@techcorp.com",
    status: TicketStatus.Resolved,
    classification: TicketClassification.GeneralQuestion,
    createdAt: new Date("2025-11-07T14:30:00Z"),
  },
  {
    subject: "Are quizzes timed?",
    body: "Before I buy the certification track I want to know — are the final exams timed or can I take as long as I need?",
    fromName: "Scarlett King",
    fromEmail: "scarlett.king@yahoo.com",
    status: TicketStatus.Resolved,
    classification: TicketClassification.GeneralQuestion,
    createdAt: new Date("2025-11-10T10:00:00Z"),
  },
  {
    subject: "Can I share my login with a colleague?",
    body: "My colleague is interested in the same course. Can we use the same account or do they need their own?",
    fromName: "George Wright",
    fromEmail: "g.wright@gmail.com",
    status: TicketStatus.Resolved,
    classification: TicketClassification.GeneralQuestion,
    createdAt: new Date("2025-11-13T16:45:00Z"),
  },
  {
    subject: "How often is course content updated?",
    body: "I'm considering the DevOps course. How frequently is the curriculum reviewed and refreshed?",
    fromName: "Victoria Harris",
    fromEmail: "victoria.harris@gmail.com",
    status: TicketStatus.Resolved,
    classification: TicketClassification.GeneralQuestion,
    createdAt: new Date("2025-11-16T11:20:00Z"),
  },
  // --- Resolved / Request ---
  {
    subject: "Request: Add bookmarking for lessons",
    body: "I'd love to be able to bookmark specific moments in a video so I can come back to key explanations.",
    fromName: "Leo Robinson",
    fromEmail: "leo.robinson@icloud.com",
    status: TicketStatus.Resolved,
    classification: TicketClassification.Request,
    createdAt: new Date("2025-11-04T08:30:00Z"),
  },
  {
    subject: "Request: Gamification badges for milestones",
    body: "It would be motivating to earn badges for finishing a course or completing a streak of daily lessons.",
    fromName: "Aria Martinez",
    fromEmail: "aria.martinez@gmail.com",
    status: TicketStatus.Resolved,
    classification: TicketClassification.Request,
    createdAt: new Date("2025-11-11T13:00:00Z"),
  },
  {
    subject: "Request: Discussion forums per course",
    body: "A place to discuss lessons with other students would greatly enhance the learning experience.",
    fromName: "Sebastian White",
    fromEmail: "sebastian.w@outlook.com",
    status: TicketStatus.Resolved,
    classification: TicketClassification.Request,
    createdAt: new Date("2025-11-19T09:50:00Z"),
  },
  {
    subject: "Request: Keyboard shortcuts for the video player",
    body: "Being able to skip forward/back 10 seconds with arrow keys, like YouTube, would make studying much faster.",
    fromName: "Penelope Jackson",
    fromEmail: "penelope.j@gmail.com",
    status: TicketStatus.Resolved,
    classification: TicketClassification.Request,
    createdAt: new Date("2025-11-23T14:15:00Z"),
  },
  // --- Resolved / Refund ---
  {
    subject: "Refund — content didn't match description",
    body: "The 'Advanced SQL' course was described as covering query optimization but it's all basic SELECT statements.",
    fromName: "Julian Lewis",
    fromEmail: "julian.lewis@protonmail.com",
    status: TicketStatus.Resolved,
    classification: TicketClassification.Refund,
    createdAt: new Date("2025-11-06T10:30:00Z"),
  },
  {
    subject: "Refund — purchased during free trial by mistake",
    body: "I didn't realise my free trial converted to a paid plan. I was charged $79. Please refund.",
    fromName: "Ellie Thompson",
    fromEmail: "ellie.thompson@yahoo.com",
    status: TicketStatus.Resolved,
    classification: TicketClassification.Refund,
    createdAt: new Date("2025-11-14T12:45:00Z"),
  },
  {
    subject: "Refund — annual plan charged instead of monthly",
    body: "I selected monthly billing but was charged the full annual amount of $199. Please correct this.",
    fromName: "Felix Anderson",
    fromEmail: "felix.anderson@gmail.com",
    status: TicketStatus.Resolved,
    classification: TicketClassification.Refund,
    createdAt: new Date("2025-11-20T09:00:00Z"),
  },
  {
    subject: "Refund — medical emergency, cannot complete course",
    body: "I was hospitalised shortly after purchasing and cannot continue. I'm requesting a compassionate refund.",
    fromName: "Isabelle Taylor",
    fromEmail: "isabelle.taylor@icloud.com",
    status: TicketStatus.Resolved,
    classification: TicketClassification.Refund,
    createdAt: new Date("2025-11-26T11:30:00Z"),
  },
  // --- Closed / TechnicalQuestion ---
  {
    subject: "Login redirects to blank page",
    body: "After I enter my credentials the page goes completely white. Clearing cache didn't help.",
    fromName: "Max Wilson",
    fromEmail: "max.wilson@gmail.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2025-09-01T08:00:00Z"),
  },
  {
    subject: "Mobile app crashes on startup",
    body: "Since the last update the iOS app crashes immediately after the splash screen.",
    fromName: "Ruby Thomas",
    fromEmail: "ruby.thomas@outlook.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2025-09-04T10:30:00Z"),
  },
  {
    subject: "Course thumbnail images broken",
    body: "All course thumbnails show broken image icons. This has been happening for two days.",
    fromName: "Oscar Moore",
    fromEmail: "oscar.moore@yahoo.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2025-09-07T13:15:00Z"),
  },
  {
    subject: "Search returning no results",
    body: "When I type 'Python' or 'JavaScript' in the search bar the results page is empty.",
    fromName: "Ivy Jackson",
    fromEmail: "ivy.jackson@gmail.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2025-09-10T09:45:00Z"),
  },
  {
    subject: "Cannot update password",
    body: "The 'Change Password' form accepts my input but shows a success message without actually changing it.",
    fromName: "Freddie Martin",
    fromEmail: "freddie.martin@hotmail.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2025-09-13T14:00:00Z"),
  },
  {
    subject: "Invoice PDF not generating",
    body: "I need invoices for expense reports. The 'Download Invoice' button does nothing on my account.",
    fromName: "Molly Garcia",
    fromEmail: "molly.garcia@gmail.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2025-09-16T11:00:00Z"),
  },
  {
    subject: "Lesson notes not saving",
    body: "I take notes directly in the lesson note-taking area but they disappear when I navigate away.",
    fromName: "Elliot Davis",
    fromEmail: "elliot.davis@protonmail.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2025-09-19T16:30:00Z"),
  },
  {
    subject: "Video stutters on 1080p setting",
    body: "720p is fine but 1080p stutters constantly even on a 200 Mbps connection.",
    fromName: "Bella Rodriguez",
    fromEmail: "bella.rodriguez@gmail.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2025-09-22T10:10:00Z"),
  },
  {
    subject: "Wrong currency charged",
    body: "I'm in the UK and should be charged in GBP but my card shows a USD charge with a conversion fee.",
    fromName: "Jasper Evans",
    fromEmail: "jasper.evans@icloud.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2025-09-25T08:50:00Z"),
  },
  {
    subject: "Unable to enrol in free course",
    body: "'Introduction to Cloud Computing' is listed as free but clicking Enrol asks me to enter payment details.",
    fromName: "Daisy Brown",
    fromEmail: "daisy.brown@yahoo.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2025-09-28T15:20:00Z"),
  },
  // --- Closed / GeneralQuestion ---
  {
    subject: "Do completed courses expire from my library?",
    body: "I finished a course a year ago. If I don't log in for a long time will it disappear?",
    fromName: "Reuben Clark",
    fromEmail: "reuben.clark@gmail.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.GeneralQuestion,
    createdAt: new Date("2025-09-02T09:00:00Z"),
  },
  {
    subject: "Is there a mobile app available?",
    body: "I prefer studying on my tablet. Is there an Android or iOS app, or is it browser-only?",
    fromName: "Luna White",
    fromEmail: "luna.white@outlook.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.GeneralQuestion,
    createdAt: new Date("2025-09-05T11:45:00Z"),
  },
  {
    subject: "Can I get a VAT invoice?",
    body: "I need a VAT invoice for my business expense claim. Can you issue one for my last purchase?",
    fromName: "Miles Thompson",
    fromEmail: "miles.thompson@company.co.uk",
    status: TicketStatus.Closed,
    classification: TicketClassification.GeneralQuestion,
    createdAt: new Date("2025-09-08T14:30:00Z"),
  },
  {
    subject: "Which courses are included in the subscription?",
    body: "I signed up for Pro but I'm not sure if all courses are included or if some are paid add-ons.",
    fromName: "Esme Patel",
    fromEmail: "esme.patel@gmail.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.GeneralQuestion,
    createdAt: new Date("2025-09-11T10:00:00Z"),
  },
  {
    subject: "How do I cancel my subscription?",
    body: "I need to cancel my monthly subscription. I've looked in account settings but can't find the option.",
    fromName: "Albie Harris",
    fromEmail: "albie.harris@yahoo.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.GeneralQuestion,
    createdAt: new Date("2025-09-14T09:30:00Z"),
  },
  // --- Closed / Request ---
  {
    subject: "Request: Add note-taking sidebar",
    body: "Having a collapsible sidebar where I could type notes while watching a video would be very useful.",
    fromName: "Bertie Lewis",
    fromEmail: "bertie.lewis@gmail.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.Request,
    createdAt: new Date("2025-09-03T08:15:00Z"),
  },
  {
    subject: "Request: Allow re-downloading completed courses",
    body: "I deleted some offline videos and now I can't re-download them. Please add this functionality.",
    fromName: "Cecily Walker",
    fromEmail: "cecily.walker@icloud.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.Request,
    createdAt: new Date("2025-09-09T13:30:00Z"),
  },
  {
    subject: "Request: Weekly study reminders via email",
    body: "A weekly email nudging me to continue my course would help keep me accountable.",
    fromName: "Rupert Hall",
    fromEmail: "rupert.hall@outlook.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.Request,
    createdAt: new Date("2025-09-17T10:00:00Z"),
  },
  {
    subject: "Request: Integrate with Notion for notes",
    body: "A Notion integration so I can export my in-app notes automatically would save me a lot of time.",
    fromName: "Clementine Young",
    fromEmail: "clem.young@gmail.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.Request,
    createdAt: new Date("2025-09-23T14:45:00Z"),
  },
  // --- Closed / Refund ---
  {
    subject: "Refund — didn't realise subscription auto-renewed",
    body: "I thought I cancelled but was charged again. I haven't used the platform in 4 months. Please refund.",
    fromName: "Edmund Clarke",
    fromEmail: "edmund.clarke@gmail.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.Refund,
    createdAt: new Date("2025-09-06T09:00:00Z"),
  },
  {
    subject: "Refund — course quality far below expectations",
    body: "The course had only 2 hours of content for a $99 price tag and most slides were just bullet points.",
    fromName: "Fern Robinson",
    fromEmail: "fern.robinson@yahoo.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.Refund,
    createdAt: new Date("2025-09-12T11:30:00Z"),
  },
  {
    subject: "Refund — bought course as a gift, recipient already has it",
    body: "I gifted 'CSS Mastery' to my nephew but he already owns it. Can I get a refund or credit?",
    fromName: "Gus Martin",
    fromEmail: "gus.martin@hotmail.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.Refund,
    createdAt: new Date("2025-09-18T13:00:00Z"),
  },
  {
    subject: "Refund — job loss, can no longer afford subscription",
    body: "I was recently made redundant and can no longer afford the subscription. Requesting a pro-rata refund.",
    fromName: "Harriet Scott",
    fromEmail: "harriet.scott@gmail.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.Refund,
    createdAt: new Date("2025-09-24T10:00:00Z"),
  },
  {
    subject: "Refund — purchased course already covered by subscription",
    body: "I accidentally bought a course individually that's already included in my Pro subscription. Please refund.",
    fromName: "Ivan Turner",
    fromEmail: "ivan.turner@protonmail.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.Refund,
    createdAt: new Date("2025-09-29T14:00:00Z"),
  },
  // --- More Open tickets to reach 100 ---
  {
    subject: "Cannot add a new payment method",
    body: "The payment settings page lets me type my card details but the Save button is permanently greyed out.",
    fromName: "Jana Novak",
    fromEmail: "jana.novak@gmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2026-01-30T09:00:00Z"),
  },
  {
    subject: "Lesson 12 video is only 3 seconds long",
    body: "In the 'TypeScript Deep Dive' course, lesson 12 loads but cuts off after 3 seconds. All others are fine.",
    fromName: "Piotr Kowalski",
    fromEmail: "piotr.k@outlook.com",
    status: TicketStatus.Open,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2026-02-01T10:30:00Z"),
  },
  {
    subject: "Do you accept PayPal?",
    body: "I don't have a credit card. Can I pay with PayPal or any other alternative payment method?",
    fromName: "Maria Santos",
    fromEmail: "maria.santos@yahoo.com",
    status: TicketStatus.Open,
    classification: TicketClassification.GeneralQuestion,
    createdAt: new Date("2026-02-02T08:45:00Z"),
  },
  {
    subject: "Request: Add a 'Most Popular' category",
    body: "It's hard to discover good courses. A curated 'Most Popular' or 'Staff Pick' section would be great.",
    fromName: "Luca Ferrari",
    fromEmail: "luca.ferrari@gmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.Request,
    createdAt: new Date("2026-02-03T14:00:00Z"),
  },
  {
    subject: "Refund — platform not compatible with company VPN",
    body: "My employer's VPN blocks the video CDN so I can't watch any lessons at work. Requesting a refund.",
    fromName: "Nina Bergstrom",
    fromEmail: "nina.bergstrom@corp.se",
    status: TicketStatus.Open,
    classification: TicketClassification.Refund,
    createdAt: new Date("2026-02-04T11:20:00Z"),
  },
  {
    subject: "Wrong name on certificate",
    body: "My certificate says 'Jon Smith' but my name is 'John Smith'. Can this be corrected?",
    fromName: "John Smith",
    fromEmail: "john.smith@gmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2026-02-05T09:10:00Z"),
  },
  {
    subject: "Is the Cloud Architecture course suitable for beginners?",
    body: "I have 6 months of IT experience. Would you recommend the Cloud Architecture course or something else first?",
    fromName: "Amara Okafor",
    fromEmail: "amara.okafor@gmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.GeneralQuestion,
    createdAt: new Date("2026-02-06T15:30:00Z"),
  },
  {
    subject: "Request: Ability to hide completed courses from dashboard",
    body: "After finishing a course I'd prefer to hide it from the main view. An archive or hide option would help.",
    fromName: "Tobias Muller",
    fromEmail: "tobias.muller@web.de",
    status: TicketStatus.Open,
    classification: TicketClassification.Request,
    createdAt: new Date("2026-02-07T10:00:00Z"),
  },
  {
    subject: "Charged twice in the same month",
    body: "I see two subscription charges dated Feb 1 and Feb 3 on my bank statement. Please investigate.",
    fromName: "Yuki Nakamura",
    fromEmail: "yuki.nakamura@gmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.Refund,
    createdAt: new Date("2026-02-08T08:00:00Z"),
  },
  {
    subject: "Sign-up email not received",
    body: "I registered 20 minutes ago but the welcome email and verification link haven't arrived. Spam folder is empty.",
    fromName: "Kenji Watanabe",
    fromEmail: "kenji.w@protonmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2026-02-09T12:40:00Z"),
  },
  {
    subject: "How do I switch from monthly to annual billing?",
    body: "I'd like to save by switching to the annual plan. Can you explain the process and whether I'll be charged immediately?",
    fromName: "Svetlana Ivanova",
    fromEmail: "svetlana.ivanova@mail.ru",
    status: TicketStatus.Open,
    classification: TicketClassification.GeneralQuestion,
    createdAt: new Date("2026-02-10T11:00:00Z"),
  },
  {
    subject: "Request: Provide transcripts for all lessons",
    body: "As a deaf learner I rely on written transcripts. Only 30% of your lessons currently have them.",
    fromName: "Thomas Dubois",
    fromEmail: "thomas.dubois@gmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.Request,
    createdAt: new Date("2026-02-11T09:30:00Z"),
  },
  {
    subject: "Refund — changed my mind within 24 hours",
    body: "I bought the course last night and realised this morning it isn't what I needed. Under 24 hours, no content watched.",
    fromName: "Ana Lima",
    fromEmail: "ana.lima@gmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.Refund,
    createdAt: new Date("2026-02-12T07:55:00Z"),
  },
  {
    subject: "Interactive exercises not grading correctly",
    body: "I enter the correct answer for the CSS selector challenge but it always marks me wrong.",
    fromName: "Khalid Al-Rashid",
    fromEmail: "khalid.rashid@gmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2026-02-13T14:20:00Z"),
  },
  {
    subject: "What IDE do instructors use in the JavaScript courses?",
    body: "The instructor's editor looks great in the screencasts. Which IDE or theme is that?",
    fromName: "Camille Petit",
    fromEmail: "camille.petit@orange.fr",
    status: TicketStatus.Open,
    classification: TicketClassification.GeneralQuestion,
    createdAt: new Date("2026-02-14T10:10:00Z"),
  },
  {
    subject: "Dropdown menus inaccessible with keyboard",
    body: "I use only keyboard navigation. The course filter dropdowns can't be opened with Enter or Space.",
    fromName: "Diane Moreau",
    fromEmail: "diane.moreau@gmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2026-02-15T09:00:00Z"),
  },
  {
    subject: "Request: Show estimated completion time per course",
    body: "Before enrolling I'd like to know how many hours of content a course contains. Please add this to the course page.",
    fromName: "Pedro Alves",
    fromEmail: "pedro.alves@gmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.Request,
    createdAt: new Date("2026-02-16T11:30:00Z"),
  },
  {
    subject: "Refund — course content is outdated",
    body: "The 'Docker Essentials' course still covers Docker 19 which is years old. The content is not usable.",
    fromName: "Ingrid Larsen",
    fromEmail: "ingrid.larsen@gmail.com",
    status: TicketStatus.Resolved,
    classification: TicketClassification.Refund,
    createdAt: new Date("2025-12-01T10:00:00Z"),
  },
  {
    subject: "Page freezes when switching between lessons quickly",
    body: "If I click the next lesson before the current video finishes loading, the entire page freezes.",
    fromName: "Stefan Gruber",
    fromEmail: "stefan.gruber@web.de",
    status: TicketStatus.Resolved,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2025-12-04T14:20:00Z"),
  },
  {
    subject: "Are there live Q&A sessions with instructors?",
    body: "I'm considering the premium tier. Does it include any live webinars or office hours with the instructors?",
    fromName: "Miriam Cohen",
    fromEmail: "miriam.cohen@gmail.com",
    status: TicketStatus.Resolved,
    classification: TicketClassification.GeneralQuestion,
    createdAt: new Date("2025-12-07T09:45:00Z"),
  },
  {
    subject: "Request: RSS feed for new course announcements",
    body: "I'd love an RSS feed so I can subscribe to new course releases without having to check the website.",
    fromName: "Bart Vermeersch",
    fromEmail: "bart.v@telenet.be",
    status: TicketStatus.Closed,
    classification: TicketClassification.Request,
    createdAt: new Date("2025-10-05T08:00:00Z"),
  },
  {
    subject: "Account locked after too many login attempts",
    body: "I forgot my password and tried a few times. Now my account is locked and the reset email isn't arriving.",
    fromName: "Olga Petrova",
    fromEmail: "olga.petrova@mail.ru",
    status: TicketStatus.Resolved,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2025-12-10T13:00:00Z"),
  },
  {
    subject: "How do I pause my subscription temporarily?",
    body: "I'm going on maternity leave for 3 months. Can I pause my subscription instead of cancelling?",
    fromName: "Chiara Rossi",
    fromEmail: "chiara.rossi@gmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.GeneralQuestion,
    createdAt: new Date("2026-02-17T10:00:00Z"),
  },
  {
    subject: "Refund — payment processed but account not upgraded",
    body: "I was charged $149 for the annual Pro plan but my account still shows the free tier.",
    fromName: "Andrei Popescu",
    fromEmail: "andrei.popescu@gmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.Refund,
    createdAt: new Date("2026-02-18T08:30:00Z"),
  },
  {
    subject: "Course search ignores accented characters",
    body: "Searching 'resume' doesn't return results that contain 'résumé'. Please fix accent-insensitive search.",
    fromName: "François Dupont",
    fromEmail: "francois.dupont@gmail.com",
    status: TicketStatus.Open,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2026-02-19T11:00:00Z"),
  },
  {
    subject: "Request: Export my learning history as CSV",
    body: "I want to track my learning over time in a spreadsheet. A CSV export of completed lessons would be very useful.",
    fromName: "Mei Lin",
    fromEmail: "mei.lin@gmail.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.Request,
    createdAt: new Date("2025-10-12T09:30:00Z"),
  },
  {
    subject: "Sidebar navigation disappears on tablet landscape mode",
    body: "When I rotate my iPad to landscape, the left navigation sidebar disappears and there's no way to bring it back.",
    fromName: "Kwame Asante",
    fromEmail: "kwame.asante@gmail.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.TechnicalQuestion,
    createdAt: new Date("2025-10-18T14:00:00Z"),
  },
  {
    subject: "Refund — accidentally bought course in wrong language",
    body: "I bought what I thought was an English course but the audio is in Portuguese with no English dubbing.",
    fromName: "Hanna Müller",
    fromEmail: "hanna.mueller@gmail.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.Refund,
    createdAt: new Date("2025-10-25T10:30:00Z"),
  },
  {
    subject: "Can I get a printed certificate mailed to me?",
    body: "My employer requires a physical certificate for CPD records. Is a printed/posted option available?",
    fromName: "Patrick O'Sullivan",
    fromEmail: "patrick.osullivan@gmail.com",
    status: TicketStatus.Closed,
    classification: TicketClassification.GeneralQuestion,
    createdAt: new Date("2025-10-30T09:00:00Z"),
  },
];

async function seedTickets() {
  const count = await prisma.ticket.count();
  if (count > 0) {
    console.log(`Tickets already seeded (${count} exist) — skipping`);
    return;
  }
  await prisma.ticket.createMany({ data: TICKETS });
  console.log(`Created ${TICKETS.length} tickets`);
}

async function seed() {
  await upsertUser("Admin", adminEmail, adminPassword, UserRole.Admin);
  await upsertUser("Agent", agentEmail, agentPassword, UserRole.Agent);
  await seedTickets();
}

seed()
  .catch((err) => {
    console.error("Seed failed:", err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
